import './globals.css'
import { Manrope } from 'next/font/google'

const manrope = Manrope({
  weight: "800",
  subsets: ['latin'],
  variable: "--font-manrope",
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${manrope.variable} flex flex-col items-center justify-center h-screen sm:flex-col bg-neutral-dark-blue`}>
        <main>
          {children}
        </main>
        <footer className="absolute justify-center hidden text-center bottom-3 sm:block sm:bottom-3">
          <p className="text-sm font-montserrat text-primary-light-cyan">
            Challenge by <span className='underline text-primary-neon-green'><a href="https://www.frontendmentor.io" rel='noopener noreferrer' target="_blank">Frontend Mentor</a></span>.
            Coded by <span className="underline text-primary-neon-green" ><a href="https://github.com/Dondamad" target="_blank" aria-label="DonnxDev">DonnxDev</a></span>.
          </p>
        </footer>
      </body>
    </html>
  )
}
